package instructions

import (
	"sort"
	"strings"
	"testing"

	"github.com/danieljustus/symaira-memory/internal/db"
)

// sizeBudget caps the embedded instruction document: it is injected into
// every agent prompt, so it must stay small enough to remain cheap context.
const sizeBudget = 16 * 1024

func TestTextNonEmpty(t *testing.T) {
	out := Text("test-version")
	if out == "" {
		t.Fatal("Text() returned empty content")
	}
	for _, marker := range []string{
		"Symaira Memory — Agent Integration Guide",
		"memory_search",
		"memory_set",
		"Scope Selection",
	} {
		if !strings.Contains(out, marker) {
			t.Errorf("Text() output missing expected marker %q", marker)
		}
	}
}

func TestTextSizeBudget(t *testing.T) {
	out := Text("test-version")
	if len(out) > sizeBudget {
		t.Errorf("embedded instructions exceed size budget: %d > %d bytes", len(out), sizeBudget)
	}
}

// TestTextDeterministic guards the byte-identical default contract: the
// default output must not change with the version argument or across calls,
// because skills/symmemory/SKILL.md and the README copy workflow depend on it.
func TestTextDeterministic(t *testing.T) {
	a := Text("v0.1.0")
	b := Text("v9.9.9")
	if a != b {
		t.Error("Text() output changed with the version argument")
	}
	if Text("v0.1.0") != a {
		t.Error("Text() output is not stable across calls")
	}
}

func TestRenderDefaultMatchesText(t *testing.T) {
	got, err := Render("v0.1.0", "", nil)
	if err != nil {
		t.Fatalf("Render(default) failed: %v", err)
	}
	if got != Text("v0.1.0") {
		t.Error("Render() with empty client differs from Text() — default output must stay byte-identical")
	}
}

func TestRenderUnknownClient(t *testing.T) {
	_, err := Render("v0.1.0", "not-a-client", nil)
	if err == nil {
		t.Fatal("Render() with unknown client did not error")
	}
	if !strings.Contains(err.Error(), "unknown client") {
		t.Errorf("error does not name the problem: %v", err)
	}
	if !strings.Contains(err.Error(), "claude-code") {
		t.Errorf("error does not list a supported client: %v", err)
	}
}

func TestRenderClientIncludesRulesAndVersion(t *testing.T) {
	rules := []*db.Rule{
		{ID: "r1", Content: "Prefer tabs over spaces in Go."},
		{ID: "r2", Content: "API daemon runs on port 8787."},
	}
	out, err := Render("9.9.9", "claude-code", rules)
	if err != nil {
		t.Fatalf("Render() failed: %v", err)
	}
	if !strings.Contains(out, "Symaira Memory — Agent Integration Guide") {
		t.Error("client render is missing the integration text")
	}
	if !strings.Contains(out, "## Behavioral Rules") {
		t.Error("client render is missing the Behavioral Rules section")
	}
	for _, r := range rules {
		if !strings.Contains(out, r.Content) {
			t.Errorf("client render is missing rule %q", r.Content)
		}
	}
	if !strings.Contains(out, "_Generated by symmemory v9.9.9._") {
		t.Error("client render is missing the version footer with the substituted version")
	}
}

// TestRenderRuleOrdering verifies deterministic output: rules render sorted
// by content (tie-break by ID), regardless of input order or DB ordering.
func TestRenderRuleOrdering(t *testing.T) {
	rules := []*db.Rule{
		{ID: "c", Content: "Zebra rule."},
		{ID: "a", Content: "Alpha rule."},
		{ID: "b", Content: "Alpha rule."},
	}
	out1, err := Render("v1", "cursor", rules)
	if err != nil {
		t.Fatalf("Render() failed: %v", err)
	}
	out2, err := Render("v1", "cursor", []*db.Rule{rules[2], rules[0], rules[1]})
	if err != nil {
		t.Fatalf("Render() failed on reordered input: %v", err)
	}
	if out1 != out2 {
		t.Error("Render() output is not stable across rule input orders")
	}
	idxAlphaFirst := strings.Index(out1, "- Alpha rule.\n")
	idxAlphaSecond := strings.Index(out1[idxAlphaFirst+1:], "- Alpha rule.\n")
	idxZebra := strings.Index(out1, "- Zebra rule.\n")
	if idxAlphaFirst < 0 || idxAlphaSecond < 0 || idxZebra < 0 {
		t.Fatalf("sorted output missing expected rules:\n%s", out1)
	}
	if idxAlphaFirst > idxZebra || idxAlphaSecond+idxAlphaFirst+1 > idxZebra {
		t.Error("rules are not sorted by content")
	}
}

func TestClientNamesSorted(t *testing.T) {
	names := ClientNames()
	if len(names) != len(clientFormats) {
		t.Fatalf("ClientNames() returned %d names for %d formats", len(names), len(clientFormats))
	}
	if !sort.StringsAreSorted(names) {
		t.Errorf("ClientNames() not sorted: %v", names)
	}
	if names[0] != "claude-code" {
		t.Errorf("expected claude-code first, got %q", names[0])
	}
}

func TestClientFormatsComplete(t *testing.T) {
	seen := map[string]bool{}
	for i := range clientFormats {
		c := &clientFormats[i]
		if c.Name == "" || c.FileName == "" || c.Description == "" {
			t.Errorf("client format %+v has empty fields", c)
		}
		if seen[c.Name] {
			t.Errorf("duplicate client name %q", c.Name)
		}
		seen[c.Name] = true
		if !ValidClient(c.Name) {
			t.Errorf("ValidClient(%q) = false for a declared format", c.Name)
		}
		fn, ok := FileNameFor(c.Name)
		if !ok || fn != c.FileName {
			t.Errorf("FileNameFor(%q) = %q, %v; want %q, true", c.Name, fn, ok, c.FileName)
		}
	}
	if _, ok := FileNameFor("bogus"); ok {
		t.Error("FileNameFor() accepted an unknown client")
	}
}
