package instructions

import (
	_ "embed"
	"fmt"
	"sort"
	"strings"

	"github.com/danieljustus/symaira-memory/internal/db"
)

//go:embed instructions.md
var instructionsText string

// versionPlaceholder is substituted with the running version where it
// appears in rendered output. The canonical embedded document does not
// contain it today, so default output stays byte-identical; client-mode
// rendering reserves it for future use.
const versionPlaceholder = "{{version}}"

// ClientFormat describes the instruction file format one AI client reads.
type ClientFormat struct {
	Name        string // CLI name used as `symmemory instructions --client <name>`
	FileName    string // destination file the client reads
	Description string
}

// clientFormats is the single source of truth for the clients the
// instructions command can render instruction files for. The hook command
// family keeps its own list (hookMCPClients) for MCP server wiring — an MCP
// host config and an instruction file are different artifacts; where a
// client appears in both, the names match.
var clientFormats = []ClientFormat{
	{Name: "claude-code", FileName: "CLAUDE.md", Description: "Claude Code (CLAUDE.md in the project root)"},
	{Name: "codex", FileName: "AGENTS.md", Description: "OpenAI Codex CLI (AGENTS.md in the project root)"},
	{Name: "opencode", FileName: "AGENTS.md", Description: "OpenCode (AGENTS.md in the project root)"},
	{Name: "cursor", FileName: ".cursorrules", Description: "Cursor (.cursorrules in the project root)"},
	{Name: "gemini", FileName: "GEMINI.md", Description: "Gemini (GEMINI.md in the project root)"},
}

// Text returns the canonical embedded instruction document. The version
// parameter is reserved for substitution via versionPlaceholder; with the
// current document (no placeholder) the output is the embedded text
// verbatim, keeping the default rendering byte-identical across releases.
func Text(version string) string {
	return strings.ReplaceAll(instructionsText, versionPlaceholder, version)
}

// ClientNames returns the sorted list of supported client names.
func ClientNames() []string {
	names := make([]string, 0, len(clientFormats))
	for i := range clientFormats {
		names = append(names, clientFormats[i].Name)
	}
	sort.Strings(names)
	return names
}

// ValidClient reports whether name is a supported instruction client.
func ValidClient(name string) bool {
	for i := range clientFormats {
		if clientFormats[i].Name == name {
			return true
		}
	}
	return false
}

// FileNameFor returns the instruction file name a client reads. The bool
// is false for unknown clients.
func FileNameFor(client string) (string, bool) {
	for i := range clientFormats {
		if clientFormats[i].Name == client {
			return clientFormats[i].FileName, true
		}
	}
	return "", false
}

// Render composes the instruction document for client. With client == ""
// it returns the canonical embedded document verbatim (byte-identical to
// Text). Otherwise it appends the stored behavioral rules for the resolved
// scope in a stable order plus a deterministic version footer.
func Render(version, client string, rules []*db.Rule) (string, error) {
	if client == "" {
		return Text(version), nil
	}
	if !ValidClient(client) {
		return "", fmt.Errorf("unknown client %q; supported clients: %s", client, strings.Join(ClientNames(), ", "))
	}

	var b strings.Builder
	b.WriteString(instructionsText)

	if len(rules) > 0 {
		b.WriteString("\n## Behavioral Rules\n\n")
		sorted := make([]*db.Rule, len(rules))
		copy(sorted, rules)
		sort.Slice(sorted, func(i, j int) bool {
			if sorted[i].Content != sorted[j].Content {
				return sorted[i].Content < sorted[j].Content
			}
			return sorted[i].ID < sorted[j].ID
		})
		for _, r := range sorted {
			b.WriteString("- ")
			b.WriteString(r.Content)
			b.WriteString("\n")
		}
	}

	b.WriteString("\n---\n")
	fmt.Fprintf(&b, "_Generated by symmemory v%s._\n", version)
	return b.String(), nil
}
