package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var configInitForce bool

func init() {
	configInitCmd.Flags().BoolVarP(&configInitForce, "force", "f", false, "Overwrite existing configuration file")
	rootCmd.AddCommand(configInitCmd)
}

var configInitCmd = &cobra.Command{
	Use:   "config init",
	Short: "Scaffold a default configuration file at the standard XDG path",
	Long: `Creates a commented TOML configuration file at ~/.config/symmemory/config.toml
with all supported fields and their default values.

The command is idempotent — it will not overwrite an existing file unless
--force is passed.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("cannot determine home directory: %w", err)
		}

		dir := filepath.Join(home, ".config", "symmemory")
		filePath := filepath.Join(dir, "config.toml")

		if !configInitForce {
			if _, err := os.Stat(filePath); err == nil {
				fmt.Fprintln(os.Stderr, "Configuration file already exists at", filePath)
				fmt.Fprintln(os.Stderr, "Use --force to overwrite.")
				return nil
			}
		}

		if err := os.MkdirAll(dir, 0700); err != nil {
			return fmt.Errorf("failed to create config directory: %w", err)
		}

		template := `# Symaira Memory Configuration
# Generated by 'symmemory config init'
# See https://github.com/danieljustus/symaira-memory for documentation.

[database]
# Path to the SQLite database file.
# Default: automatically placed in ~/.config/symmemory/
# path = ""

[ollama]
# URL of the Ollama embeddings API endpoint.
url = "http://localhost:11434/api/embeddings"

# Embedding model to use for semantic search.
model = "nomic-embed-text"

[jwt]
# Path to the JWT signing secret file.
# Default: ~/.config/symmemory/jwt.secret (auto-generated on first use)
# secret_path = ""

# Vault URI for the JWT signing secret.
# When set, resolves via "symvault get <path> --print" subprocess (5s timeout).
# Falls back to JWT_SECRET_KEY env var if symvault is unavailable.
# secret = "vault://symaira/memory/jwt"

[security]
# Enable automatic PII (email, API keys, credit cards) redaction before storage.
pii_enabled = true

[server]
# HTTP port for the REST API daemon (0 = disabled, stdio-only).
http_port = 0
`
		if err := os.WriteFile(filePath, []byte(template), 0600); err != nil {
			return fmt.Errorf("failed to write config file: %w", err)
		}

		fmt.Fprintf(os.Stderr, "Configuration file created: %s\n", filePath)
		return nil
	},
}
