package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var configInitForce bool

func init() {
	configInitCmd.Flags().BoolVarP(&configInitForce, "force", "f", false, "Overwrite existing configuration file")
	rootCmd.AddCommand(configInitCmd)
}

var configInitCmd = &cobra.Command{
	Use:   "config init",
	Short: "Scaffold a default configuration file at the standard XDG path",
	Long: `Creates a commented TOML configuration file at ~/.config/symmemory/config.toml
with all supported fields and their default values.

The command is idempotent — it will not overwrite an existing file unless
--force is passed.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("cannot determine home directory: %w", err)
		}

		dir := filepath.Join(home, ".config", "symmemory")
		filePath := filepath.Join(dir, "config.toml")

		if !configInitForce {
			if _, err := os.Stat(filePath); err == nil {
				fmt.Fprintln(os.Stderr, "Configuration file already exists at", filePath)
				fmt.Fprintln(os.Stderr, "Use --force to overwrite.")
				return nil
			}
		}

		if err := os.MkdirAll(dir, 0700); err != nil {
			return fmt.Errorf("failed to create config directory: %w", err)
		}

		template := `# Symaira Memory Configuration
# Generated by 'symmemory config init'
# See https://github.com/danieljustus/symaira-memory for documentation.

[database]
# Path to the SQLite database file.
# Default: automatically placed in ~/.config/symmemory/
# path = ""

[ollama]
# URL of the Ollama embeddings API endpoint.
url = "http://localhost:11434/api/embeddings"

# Embedding model to use for semantic search.
model = "nomic-embed-text"

[jwt]
# Path to the JWT signing secret file.
# Default: ~/.config/symmemory/jwt.secret (auto-generated on first use)
# secret_path = ""

# Vault URI for the JWT signing secret.
# When set, resolves via "symvault get <path> --print" subprocess (5s timeout).
# Falls back to JWT_SECRET_KEY env var if symvault is unavailable.
# secret = "vault://symaira/memory/jwt"

[security]
# Enable automatic PII (email, API keys, credit cards) redaction before storage.
pii_enabled = true

[server]
# HTTP port for the REST API daemon (0 = disabled, stdio-only).
http_port = 0

[ranking]
# Weights for composite retrieval scoring (relevance + recency + importance).
# All three weights are normalized, so relative values matter more than absolute.
relevance_weight = 0.6
recency_weight = 0.2
importance_weight = 0.2
# Half-life in days for recency decay (default: 30 days).
recency_half_life = 30

[context]
# Token budget for context assembly (max tokens for assembled context).
token_budget = 2000
# Budget allocation for each layer.
working_context_tokens = 500
summary_tokens = 500
retrieval_tokens = 1000
# Max recent conversation turns to include in working context.
max_working_turns = 5

[retention]
# Session-scoped memory TTL (default: "720h" = 30 days).
session_ttl = "720h"
# Enable automatic background purge of expired memories.
auto_purge_enabled = false
# Enable append-only audit log for memory mutations.
audit_log_enabled = true
# How long to retain audit log entries (default: "720h" = 30 days).
audit_retention = "720h"

[hybrid_search]
# Enable hybrid vector + BM25 keyword search.
enabled = true
# Weights for score fusion (Reciprocal Rank Fusion).
bm25_weight = 0.3
vector_weight = 0.7
# Enable Maximal Marginal Relevance diversity re-ranking.
mmr_enabled = false
# MMR lambda: 0.0 = pure diversity, 1.0 = pure relevance.
mmr_lambda = 0.7
`
		if err := os.WriteFile(filePath, []byte(template), 0600); err != nil {
			return fmt.Errorf("failed to write config file: %w", err)
		}

		fmt.Fprintf(os.Stderr, "Configuration file created: %s\n", filePath)
		return nil
	},
}
