package cmd

import (
	"bytes"
	"os"
	"strings"
	"testing"

	"github.com/danieljustus/symaira-memory/internal/config"
	"github.com/danieljustus/symaira-memory/internal/db"
	"github.com/danieljustus/symaira-memory/internal/instructions"
	"github.com/spf13/cobra"
)

func TestInstructionsCommandRegistered(t *testing.T) {
	for _, cmd := range rootCmd.Commands() {
		if cmd.Use == "instructions" {
			if cmd.Short == "" {
				t.Error("instructions command has empty Short description")
			}
			return
		}
	}
	t.Error("instructions command not registered on rootCmd")
}

func TestInstructionsCommandFlags(t *testing.T) {
	var insCmd *cobra.Command
	for _, cmd := range rootCmd.Commands() {
		if cmd.Use == "instructions" {
			insCmd = cmd
			break
		}
	}
	if insCmd == nil {
		t.Fatal("instructions command not found")
	}
	tests := []struct {
		name         string
		flagName     string
		defaultValue string
	}{
		{"client flag", "client", ""},
		{"output flag", "output", ""},
		{"scope flag", "scope", "global"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			flag := insCmd.Flags().Lookup(tt.flagName)
			if flag == nil {
				t.Fatalf("expected %q flag on instructions command", tt.flagName)
			}
			if flag.DefValue != tt.defaultValue {
				t.Errorf("expected default %q for flag %q, got %q", tt.defaultValue, tt.flagName, flag.DefValue)
			}
		})
	}
}

// TestInstructionsBypassesPersistentPreRunE keeps the default path free of
// database/config side effects: `symmemory instructions` must work on a
// machine with no config at all.
func TestInstructionsBypassesPersistentPreRunE(t *testing.T) {
	for _, cmd := range rootCmd.Commands() {
		if cmd.Use == "instructions" {
			if err := rootCmd.PersistentPreRunE(cmd, nil); err != nil {
				t.Errorf("instructions command should bypass PersistentPreRunE, got error: %v", err)
			}
			return
		}
	}
	t.Error("instructions command not found")
}

func TestInstructionsDefaultOutputByteIdentical(t *testing.T) {
	oldClient := instructionsClient
	instructionsClient = ""
	defer func() { instructionsClient = oldClient }()

	out := captureInstructionsOutput(t)
	want := instructions.Text(Version)
	if strings.TrimSpace(out) != strings.TrimSpace(want) {
		t.Errorf("default instructions output differs from canonical text\n--- got ---\n%s\n--- want ---\n%s", out, want)
	}
}

func TestInstructionsUnknownClientError(t *testing.T) {
	oldClient := instructionsClient
	instructionsClient = "not-a-client"
	defer func() { instructionsClient = oldClient }()

	if err := instructionsCmd.RunE(instructionsCmd, nil); err == nil {
		t.Fatal("instructions with unknown client did not error")
	} else {
		if !strings.Contains(err.Error(), "supported clients") {
			t.Errorf("error does not name the supported set: %v", err)
		}
		if !strings.Contains(err.Error(), "claude-code") {
			t.Errorf("error does not list claude-code: %v", err)
		}
	}
}

func TestInstructionsClientModeIncludesStoredRules(t *testing.T) {
	database := helperTestDB(t)
	SetConfig(config.Defaults())
	SetDB(database)
	defer func() {
		SetDB(nil)
		SetConfig(nil)
	}()

	rule := &db.Rule{
		ID:      "instr-test-rule",
		Content: "Always run gofmt before committing.",
		Scope:   "global",
		Metadata: map[string]string{
			"source": "cli_rule_add",
		},
	}
	if err := database.SaveRule(rule); err != nil {
		t.Fatalf("failed to save test rule: %v", err)
	}

	oldClient := instructionsClient
	oldScope := instructionsScope
	instructionsClient = "claude-code"
	instructionsScope = "global"
	defer func() {
		instructionsClient = oldClient
		instructionsScope = oldScope
	}()

	out := captureInstructionsOutput(t)
	if !strings.Contains(out, "## Behavioral Rules") {
		t.Error("client mode output missing Behavioral Rules section")
	}
	if !strings.Contains(out, "Always run gofmt before committing.") {
		t.Error("client mode output missing the stored rule")
	}
	if !strings.Contains(out, "Generated by symmemory v"+Version) {
		t.Error("client mode output missing the version footer")
	}
}

// captureInstructionsOutput runs the instructions command and returns its
// stdout, restoring os.Stdout afterwards.
func captureInstructionsOutput(t *testing.T) string {
	t.Helper()
	var buf bytes.Buffer
	oldStdout := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w

	// Read the pipe concurrently: on Windows the pipe buffer is ~4KB
	// (vs 64KB on Unix), so the instruction document (~6KB) blocks the
	// writer forever if the reader only starts after RunE returns.
	done := make(chan struct{})
	go func() {
		buf.ReadFrom(r)
		close(done)
	}()

	err := instructionsCmd.RunE(instructionsCmd, nil)

	_ = w.Close()
	os.Stdout = oldStdout
	<-done

	if err != nil {
		t.Fatalf("instructionsCmd.RunE returned error: %v", err)
	}
	return buf.String()
}
